export const categoriesMap = {
  accessories: ['Utility'],
  audio: ['Audio', 'Music'],
  communication: [
    'Chat',
    'ContactManagement',
    'Email',
    'InstantMessaging',
    'IRCClient',
    'Telephony',
    'VideoConference',
  ],
  development: [
    'Database',
    'Debugger',
    'Development',
    'GUIDesigner',
    'IDE',
    'RevisionControl',
    'TerminalEmulator',
    'WebDevelopment',
  ],
  education: ['Education'],
  finance: ['Economy', 'Finance'],
  games: [
    'ActionGame',
    'AdventureGame',
    'Amusement',
    'ArcadeGame',
    'BlocksGame',
    'BoardGame',
    'CardGame',
    'Game',
    'KidsGame',
    'LogicGame',
    'RolePlaying',
    'Shooter',
    'Simulation',
    'SportsGame',
    'StrategyGame',
  ],
  graphics: [
    '2DGraphics',
    '3DGraphics',
    'Graphics',
    'ImageProcessing',
    'Photography',
    'RasterGraphics',
    'VectorGraphics',
  ],
  internet: ['Network', 'P2P'],
  science: [
    'ArtificialIntelligence',
    'Astronomy',
    'Biology',
    'Calculator',
    'Chemistry',
    'ComputerScience',
    'DataVisualization',
    'Electricity',
    'Electronics',
    'Engineering',
    'Geology',
    'Geoscience',
    'Math',
    'NumericalAnalysis',
    'Physics',
    'Robotics',
    'Science',
  ],
  'media-production': [
    'AudioVideoEditing',
    'Midi',
    'Mixer',
    'Recorder',
    'Sequencer',
  ],
  office: [
    'Office',
    'Presentation',
    'Publishing',
    'Spreadsheet',
    'WordProcessor',
  ],
  'privacy-security': ['Security'],
  system: ['Monitor', 'System'],
  accessibility: ['Accessibility'],
  video: ['Tuner', 'TV', 'Video'],
  'writing-language': [
    'Dictionary',
    'Languages',
    'Literature',
    'OCR',
    'TextEditor',
    'TextTools',
    'Translation',
    'WordProcessor',
  ],
};
